version: "3.9"
services:
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.steffenebertweb.entrypoints=websecure"
      - "traefik.http.routers.steffenebertweb.rule=Host(`steffencodes.proqrent.de`)"
      - "traefik.http.routers.steffenebertweb.tls=true"
      - "traefik.http.routers.steffenebertweb.tls.certresolver=basic"
      - "traefik.http.services.steffenebertweb.loadbalancer.server.port=80"
      - "traefik.http.services.steffenebertweb.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.steffenebertweb.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.steffenebertweb.loadbalancer.healthcheck.timeout=9s"

